### ISSUE TITLE
HOW to export the fitted Bundle Adjustment Model to predict new_landmark.json

### ISSUE THREAD

**Issue by chenxinfeng4** [cvlab-epfl/multiview_calib#1]
I have ground-true data to fit a Bundle Adjustment Model, and want to predict in the following dataset. How to do that.

**Comment by lcit** [comment]
I am not sure I understood your question. If you want to triangulate unseen 2D image points you can use the script `python triangulate_image_points.py -p poses.json -l landmarks.json`. It takes some 2D points in each view and the poses that you have computed using the calibration tool. The poses can be either the one in _output/relative_poses/poses.json_ which are relative to the first camera and up to scale or the ones in _output/global_registration/global_poses.json_ which are expressed in world coordinate with correct scale (admitting you computed them the correct way of course). Another option is to use standardt OpenCV function for triangulation https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#gad3fc9a0c82b08df034234979960b778c.

**Comment by chenxinfeng4** [comment]
Well, the `triangulate_image_points.py` help me a lot. The procedure is `landmark + Pose -> build_input (points_3d) -> bundle_adjustment -> point_3D_refined`.  I can use bundle_adjustment  to refine seen train dataset. **However, the unseen 2D image points will undergo a totally new bundle_adjustment** without the correlation from the train dataset.

For example, what if I have 10000 points for training, but 2 unseen points for testing. Is that test points still precise to use `bundle_adjustment`.

**Comment by lcit** [comment]
If you obtained a proper calibration for a set of cameras then unseen/additional image points will project correctly.

**Comment by chenxinfeng4** [comment]
Ohh, I got it.
Here is my 3D reconstruction for a rat. Very thanks for your awesome tool.
![image](https://user-images.githubusercontent.com/17546446/141941251-f06e0f94-92aa-4a3e-a81f-786ec328f430.png)
