### ISSUE TITLE
space coordinates.

### ISSUE THREAD

**Issue by wagaabderrahim** [cvlab-epfl/multiview_calib#10]
thank you very much for your work 
i've tested the code in the "simple box" part my objective is to have information on the max and min depth of the real scene after calibration to generate a file that gathers this shape and i'm very interested by the last part of the json **Space** file.

`{
    "Cameras": [
        {
            "CameraId": 4,
            "ExtrinsicParameters": {
                "Rotation": [
                    -0.9194681518368479,
                    -0.21118621900988643,
                    0.33163036449945144,
                    -0.3897800999539663,
                    0.6000722379215305,
                    -0.698559076210253,
                    -0.051476124928036215,
                    -0.771565739374264,
                    -0.6340634971248846
                ],
                "Translation": [
                    -2195.9698549389072,
                    2582.5504911658027,
                    2490.1038987563416
                ]
            },
            "IntrinsicParameters": {
                "Fx": 307.77099609375,
                "Fy": 307.788330078125,
                "Cx": 319.5019938151042,
                "Cy": 184.57267252604166
            }
        },
        {
            "CameraId": 1,
            "ExtrinsicParameters": {
                "Rotation": [
                    -0.4439462674972459,
                    0.460895247104731,
                    -0.7684317033878365,
                    0.8959696690776023,
                    0.24005144953184204,
                    -0.3736491050044587,
                    0.012250047682980547,
                    -0.8543716245135546,
                    -0.5195181070548308
                ],
                "Translation": [
                    2161.74275709583,
                    1844.4107072755498,
                    2436.118150240347
                ]
            },
            "IntrinsicParameters": {
                "Fx": 307.72467041015625,
                "Fy": 307.7620035807292,
                "Cx": 320.15032958984375,
                "Cy": 182.17032877604166
            }
        },
        {
            "CameraId": 2,
            "ExtrinsicParameters": {
                "Rotation": [
                    0.36895802400698796,
                    0.5464693605319308,
                    -0.7518252553091587,
                    0.9273944609865834,
                    -0.16273486022980177,
                    0.3368336072861343,
                    0.06172106813934608,
                    -0.821516039566976,
                    -0.5668349905236343
                ],
                "Translation": [
                    2510.495174013393,
                    -1799.946577189888,
                    2503.553348475469
                ]
            },
            "IntrinsicParameters": {
                "Fx": 304.98834228515625,
                "Fy": 304.95933024088544,
                "Cx": 318.70200602213544,
                "Cy": 182.6723429361979
            }
        },
        {
            "CameraId": 3,
            "ExtrinsicParameters": {
                "Rotation": [
                    0.6863996729195561,
                    -0.5275711519231292,
                    0.5005238942092867,
                    -0.7271213831076989,
                    -0.48629312754448173,
                    0.4845755754581046,
                    -0.012246764612468042,
                    -0.6965541427351567,
                    -0.7173997093636277
                ],
                "Translation": [
                    -2700.9686290823065,
                    -2593.2363175675873,
                    2573.2628666117216
                ]
            },
            "IntrinsicParameters": {
                "Fx": 305.26633707682294,
                "Fy": 305.1856689453125,
                "Cx": 317.8646647135417,
                "Cy": 183.9866739908854
            }
        }
    ],
    "Space": {
        "MaxU": 2860,
        "MinU": -4200,
        "MaxV": 3180,
        "MinV": -2960,
        "MaxW": 2100,
        "MinW": 100,
        "VoxelSizeInMM": 20
    }

> }`

**Comment by lcit** [comment]
if you want a 3D bounding box around the object in the scene, you can obtain it easily from the triangulated landmarks i.e. the points in 'global_triang_points.json' after the global registration

**Comment by wagaabderrahim** [comment]
Thank you for your response. Indeed, to obtain the complete 3D representation of an object in the scene, I understand that it is necessary to recover its 3D bounding box. However, I would like to clarify how to retrieve the total depth of the environment along the three axes (X, Y, Z), as indicated in the camera's calibration file __ 
Knowing that I have multiple cameras. . Thank you in advance for any clarification you can provide.

**Comment by lcit** [comment]
I do not understand what you mean with total depth. And the JSON file you posted is not generated by this repository. I do not know what the values mean.

**Comment by wagaabderrahim** [comment]
As you can see in the file, we have this section:

"Space": {
"MaxU": 2860,
"MinU": -4200,
"MaxV": 3180,
"MinV": -2960,
"MaxW": 2100,
"MinW": 100,
"VoxelSizeInMM": 20
}

But at the same time, I have multiple cameras, and each camera has intrinsic and extrinsic parameters. Therefore, these parameters represent the minimum and maximum values of each axis in the real scene.
I want to retrieve these values because we performed triangulation using 4 cameras, and I still have these values that I need to recover.
