### ISSUE TITLE
build_input is too slow

### ISSUE THREAD

**Issue by chenxinfeng4** [cvlab-epfl/multiview_calib#3]
I have 6-camera x 200k frames x 10 points to calculate the 3D points. The `triangulate_image_points.py` may take my 10 hours to finsh. Can you speed up the `build_input` by numpy functions?

**Comment by lcit** [comment]
If you have that many points I suggest to triangulate them using a linear method only. You could use [OpenCV triangulation](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#gad3fc9a0c82b08df034234979960b778c) method or via Direct Linear Transform (DLT) [as in here](https://github.com/karfly/learnable-triangulation-pytorch/blob/9d1a26ea893a513bdff55f30ecbfd2ca8217bf5d/mvn/utils/multiview.py#L113). The OpenCV function takes only two views as input. To take all of them into account you could triangulate from all pairs of views then average the results as in here: https://github.com/cvlab-epfl/multiview_calib/blob/5234fd34fada07a58c5356ed706beecd56008c53/multiview_calib/bundle_adjustment_scipy.py#L311

**Comment by chenxinfeng4** [comment]
I've improved the `build_input` and `triangulate_all_pairs` greatly -- from 10+hours inference time to just 5 minutes. I will submit the code.

**Comment by lcit** [comment]
Your proposed function is not compatible atm. Can you have a look at that?
