### ISSUE TITLE
Question about the fixed_scale value

### ISSUE THREAD

**Issue by aligeniewcp22** [cvlab-epfl/multiview_calib#5]
Hi, thanks for your contributions.
I am trying to use your calibration tool, but find the problem in the final global registration step. There is an error in Line 110-114 of "multiview_calib/multiview_calib/point_set_registration.py", i.e.,

    def point_set_registration(src, dst, fixed_scale=None, verbose=True):
    ...
    if fixed_scale is not None:

        _, R, t, _ = procrustes_registration(_src*fixed_scale, _dst)

        scale = fixed_scale

    else:

        scale, R, t, _ = procrustes_registration(_src*fixed_scale, _dst)

Error messages: 

  File "/Users/wuchengpeng/HandGesture/Code/multiview_calib/multiview_calib/point_set_registration.py", line 114, in point_set_registration
    scale, R, t, _ = procrustes_registration(_src*fixed_scale, _dst)
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

I thick the if-else sentences may have some problems. Can you give some suggestions?

**Comment by lcit** [comment]
Hi thanks for pointing this out. I am surprised I missed this problem, but now it is fixed.
