### ISSUE TITLE
Question about the descriptions in docs/main.pdf

### ISSUE THREAD

**Issue by aligeniewcp22** [cvlab-epfl/multiview_calib#6]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/103427193/163090198-143351fa-f274-4139-84cc-562936a61001.png">

First, in the last paragraph of page 3, you said the example checkerboard has 6 x 8 inner corners (also in the intrinsics estimation parameters "-ich 6 -ics 8"), but the caption of figure 4 points out the number of  inner corners is 6 x 9, which is shown in the image above. So can you give me a clear answer which one is right?

Second, in the equation (6) of page 5, the projection function term in the object function of bundle adjustment is "Q(C_i, X_j)-x_j", which I think may be "Q(C_i, X_i)-X_j". I am not familiar with BA method, so may be you can re-check the equation.

Also, thanks for your immediate response about the issue yesterday.

**Comment by aligeniewcp22** [comment]
About the first question, I find that the inner corners in Figure 1 of docs/tutorial.pdf is exactly 6 x 8, so may be you can update Figure 4 in docs/main.pdf.

Moreover, the checkerboard link (https://markhedleyjones.com/storage/checkerboards/Checkerboard-A4-30mm-8x6.pdf) is unavailable. Can you provide an alternative link? Thank you very much.

**Comment by lcit** [comment]
You can use any checkerboard as long as you set -ich and -ics correctly. Eq. 6 is correct. Bundle adjustment minimizes the difference between projected 3D points (which are 2D points) and annotated images points.

https://markhedleyjones.com/projects/calibration-checkerboard-collection
