### ISSUE TITLE
Cite your work in paper.

### ISSUE THREAD

**Issue by chenxinfeng4** [cvlab-epfl/multiview_calib#8]
The multiview calibration code really works for me. I've customed some functions on my own to support further study. 

So, I will give my thanks to your great work, and I want to cite the this. Do you have any paper related to this work?

**Comment by lcit** [comment]
Thank you. Glad it was useful! I do not really have a paper specifically for this code. If you want, put a reference to this repo. Cheers

**Comment by chenxinfeng4** [comment]
I've create a new `tutorial` based on your repo.  `https://github.com/chenxinfeng4/multiview_ball_calib`.

As for citation, I think those may be closed to your work.

+ [Single-ball calibration] Perez-Cortes, Juan-Carlos, et al. "A system for in-line 3D inspection without hidden surfaces." Sensors 18.9 (2018): 2993.
+ [Multi-ball calibration] Perez, Alberto J., Juan-Carlos Perez-Cortes, and Jose-Luis Guardiola. "Simple and precise multi-view camera calibration for 3D reconstruction." Computers in Industry 123 (2020): 103256.
+ [Triple-ball calibration] 吴福朝，王亮，胡占义. “一种对多相机系统的标定方法及装置” . 发明专利 (2008): CN 101226638A
